<?php

namespace Database\Seeders;

use App\Models\ServiceCategory;
use App\Models\ServiceItem;
use Illuminate\Database\Seeder;

class LaserTreatmentsSeeder extends Seeder
{
    public function run(): void
    {
        $category = ServiceCategory::where('slug', 'laser-treatments')->first();

        if (!$category) {
            $category = ServiceCategory::create([
                'name_en' => 'Laser Treatments',
                'name_mk' => 'Ласерски третмани',
                'slug' => 'laser-treatments',
                'parent_type' => 'laser_aesthetic',
                'description_en' => 'At Babor Medical, we don\'t view laser treatments as isolated procedures, but as part of carefully crafted personalized protocols. Every skin has a different structure, different history and different needs. That\'s why our approach is based on precise assessment and selection of appropriate technology at the right moment. Our strategy is not "one device for all", but a combination of technologies with clear clinical logic.',
                'description_mk' => 'Во Babor Medical, ласерските третмани не ги гледаме како поединечни процедури, туку како дел од внимателно креирани персонализирани протоколи. Секоја кожа има различна структура, различна историја и различни потреби. Затоа нашиот пристап се базира на прецизна проценка и избор на соодветна технологија во вистинскиот момент. Нашата стратегија не е „еден апарат за сите", туку комбинација на технологии со јасна клиничка логика.',
                'display_type' => 'cards',
                'is_active' => true,
                'sort_order' => 1,
                'extra_data_en' => [
                    'treatment_areas' => [
                        'Pigmentation and sun damage',
                        'Vascular changes and redness',
                        'Unwanted hair',
                        'Scars and post-acne changes',
                        'Uneven texture and enlarged pores',
                        'Signs of aging and loss of elasticity',
                        'Overall improvement of skin quality and tone',
                    ],
                    'approach_strategies' => [
                        'Laser + collagen stimulators',
                        'Laser + RF technologies',
                        'Laser + medical cosmetology (Babor Clinical programs)',
                        'Phased treatment with clearly defined sequence',
                    ],
                    'assessment_points' => [
                        'which technology is most appropriate',
                        'how many treatments are needed',
                        'at what intensity',
                        'whether a combined strategy is needed',
                    ],
                ],
                'extra_data_mk' => [
                    'treatment_areas' => [
                        'Пигментации и сончеви оштетувања',
                        'Васкуларни промени и црвенило',
                        'Нежелана влакнетост',
                        'Лузни и постакне промени',
                        'Нерамна текстура и проширени пори',
                        'Знаци на стареење и губење на еластичност',
                        'Општо подобрување на квалитетот и тонусот на кожата',
                    ],
                    'approach_strategies' => [
                        'Ласер + колаген стимулатори',
                        'Ласер + RF технологии',
                        'Ласер + медицинска козметологија (Babor Clinical програми)',
                        'Фазен третман со јасно дефиниран редослед',
                    ],
                    'assessment_points' => [
                        'која технологија е најсоодветна',
                        'колку третмани се потребни',
                        'со каков интензитет',
                        'дали е потребна комбинирана стратегија',
                    ],
                ],
                'price_list_items_mk' => [
                     ['name' => 'Alma Soprano Titanium - Епилација надусници', 'price' => 1240],
                    ['name' => 'Alma Soprano Titanium - Епилација образи, бекенбарди', 'price' => 1500],
                    ['name' => 'Alma Soprano Titanium - Епилација брада', 'price' => 1240],
                    ['name' => 'Alma Soprano Titanium - Епилација преден дел на врат', 'price' => 1500],
                    ['name' => 'Alma Soprano Titanium - Епилација цело лице', 'price' => 4000],
                    ['name' => 'Alma Soprano Titanium - Епилација пазуви', 'price' => 2000],
                    ['name' => 'Alma Soprano Titanium - Епилација подлактици', 'price' => 2500],
                    ['name' => 'Alma Soprano Titanium - Епилација надлактици', 'price' => 2500],
                    ['name' => 'Alma Soprano Titanium - Епилација цели раце', 'price' => 4340],
                    ['name' => 'Alma Soprano Titanium - Епилација бразилска', 'price' => 3720],
                    ['name' => 'Alma Soprano Titanium - Епилација задник', 'price' => 3900],
                    ['name' => 'Alma Soprano Titanium - Епилација Кичма', 'price' => 2000],
                    ['name' => 'Alma Soprano Titanium - Епилација грб', 'price' => 4000],
                    ['name' => 'Alma Soprano Titanium - Епилација плиток препон', 'price' => 2490],
                    ['name' => 'Alma Soprano Titanium - Епилација надколена со колена', 'price' => 5590],
                    ['name' => 'Alma Soprano Titanium - Епилација подколена со колена', 'price' => 4980],
                    ['name' => 'Alma Soprano Titanium - Епилација надколена без колена', 'price' => 4100],
                    ['name' => 'Alma Soprano Titanium - Епилација подколена без колена', 'price' => 3500],
                    ['name' => 'Alma Soprano Titanium - Епилација цели нозе со плиток препон', 'price' => 12400],
                    ['name' => 'Alma Soprano Titanium - Епилација цели нозе', 'price' => 9910],
                    ['name' => 'Alma Soprano Titanium - Епилација стомачна линија', 'price' => 1500],
                    ['name' => 'Alma Soprano Titanium - Епилација цел стомак', 'price' => 3450],
                    ['name' => 'Alma Soprano Titanium - Епилација за мажи - врат', 'price' => 2480],
                    ['name' => 'Alma Soprano Titanium - Епилација за мажи - рамена', 'price' => 3720],
                    ['name' => 'Alma Soprano Titanium - Епилација за мажи- раце', 'price' => 5580],
                    ['name' => 'Alma Soprano Titanium - Епилација за мажи- гради и стомак', 'price' => 8680],
                    ['name' => 'Alma Soprano Titanium - Епилација за мажи- гради', 'price' => 4500],
                    ['name' => 'Alma Soprano Titanium - Епилација за мажи- stomak', 'price' => 4500],
                    ['name' => 'Alma Soprano Titanium - Епилација за мажи - грб', 'price' => 4340],
                    ['name' => 'Alma Soprano Titanium - Епилација за мажи - подколена', 'price' => 5800],
                    ['name' => 'Alma Soprano Titanium - Епилација за мажи – нозе', 'price' => 12400],
                    ['name' => 'Alma Soprano Titanium - Епилација за мажи - гради, стомак и грб', 'price' => 12400],
                    ['name' => 'Alma Soprano Titanium - Епилација за мажи – образи', 'price' => 2000],
                    ['name' => 'Alma Soprano Titanium - Епилација маски обликување брада', 'price' => 4000],
                    ['name' => 'Alma Soprano Titanium - Епилација мажи преден дел врат', 'price' => 2000],
                    ['name' => 'Alma Soprano Titanium - Епилација мажи преден дел врат+заден', 'price' => 2500],
                    ['name' => 'Alma Soprano Titanium - Епилација цело тело жени 1 третман', 'price' => 18500],
                    ['name' => 'Alma Soprano Titanium - Епилација цело тело жени 1 третман во пакет', 'price' => 15400],
                    ['name' => 'Alma Soprano Titanium - Епилација цело тело МАЖИ 1 третман', 'price' => 24600],
                    ['name' => 'Alma Soprano Titanium - Епилација цело тело МАЖИ 1 третман во пакет', 'price' => 21600],
                    ['name' => 'Alma Soprano Titanium - Пакет од 6 третмани МАЖИ', 'price' => 147600],
                    ['name' => 'Alma Q Lift & Tight лице', 'price' => 25000],
                    ['name' => 'Alma Q Lift & Tight лице и врат', 'price' => 37200],
                    ['name' => 'Alma Q Lift & Tight врат', 'price' => 18600],
                    ['name' => 'Alma Q третман за околуочна регија', 'price' => 3100],
                    ['name' => 'Alma Q третман за уста', 'price' => 3100],
                    ['name' => 'Alma Q избелување подочници', 'price' => 4000],
                    ['name' => 'Alma Hybrid', 'price' => 24000],
                    ['name' => 'Alma Hybrid уста', 'price' => 3000],
                    ['name' => 'Alma Hybrid очи', 'price' => 18500],
                    ['name' => 'Allma Hybrid Soft Lift', 'price' => 15000],
                    ['name' => 'Alma Titanium NIR', 'price' => 4000],
                    ['name' => 'Accent Prime подбрадок со РФ+УЗ', 'price' => 4500],
                    ['name' => 'Accent Prime врат и деколте со РФ', 'price' => 4500],
                    ['name' => 'Accent Prime РФ на цело лице', 'price' => 5000],
                    ['name' => 'Accent Prime Pixel', 'price' => 6000],
                    ['name' => 'Accent Prime Colibri', 'price' => 3000],
                    ['name' => 'Accent Prime на тело', 'price' => 2000],
                    ['name' => 'Accent Prime на тело', 'price' => 3000],
                    ['name' => 'Accent Prime стрии', 'price' => 6000],
                    ['name' => 'Ultraformer lice', 'price' => 43000],
                    ['name' => 'Ultraformer lice bez celo', 'price' => 31000],
                    ['name' => 'Ultraformer подбрадок', 'price' => 12400],
                    ['name' => 'Ultraformer врат', 'price' => 18500],
                    ['name' => 'EM Time 1 Lice', 'price' => 3500],
                    ['name' => 'Hydra Facial SYGNITURE', 'price' => 6000],
                    ['name' => 'Hydra Facial DE LUXE', 'price' => 8000],
                    ['name' => 'Hydra Facial PLATINUM', 'price' => 10000],
                    ['name' => 'Hydra Facial Jlo', 'price' => 12000],
                    ['name' => 'Alma Q Carbon Peeling', 'price' => 4000],
                    ['name' => 'Alma Hybrid', 'price' => 24000],
                    ['name' => 'Alma Hybrid папиломи', 'price' => 3000],
                    ['name' => 'Allma Hybrid мала лузна', 'price' => 10000],
                    ['name' => 'Accent Prime стрии', 'price' => 6000],
                    ['name' => 'Alma Q розацеа', 'price' => 4200],
                    ['name' => 'Alma Q розацеа ПАКЕТ 6 ТРЕТМАНИ', 'price' => 20000],
                    ['name' => 'Alma Q МЕЛАЗМА 1 ТРЕТМАН', 'price' => 15500],
                    ['name' => 'Alma Q капилари', 'price' => 3000],
                    ['name' => 'Alma Q третман на нокти', 'price' => 2000],
                    ['name' => 'Alma Q третман за веѓи', 'price' => 3100],
                    ['name' => 'PRX Пилинг', 'price' => 4800],
                    ['name' => 'Хемиски пилинг', 'price' => 4000],
                    ['name' => 'Био Ц Хемиски пилинг', 'price' => 3600],
                    ['name' => 'Био Ц Хемиски пилинг + Микронидлинг', 'price' => 6500],
                    ['name' => 'Хемиски пилинг за околуочна регија - 6 тертмани', 'price' => 12000],
                    ['name' => 'Микронидлинг', 'price' => 4500],
                    ['name' => 'Микронидлинг со Impact', 'price' => 5500],
                ],
                'price_list_items_en' => [
                      ['name' => 'Alma Soprano Titanium - Hair removal upper lip', 'price' => 1240],
                    ['name' => 'Alma Soprano Titanium - Hair removal cheeks, sideburns', 'price' => 1500],
                    ['name' => 'Alma Soprano Titanium - Hair removal chin', 'price' => 1240],
                    ['name' => 'Alma Soprano Titanium - Hair removal front of neck', 'price' => 1500],
                    ['name' => 'Alma Soprano Titanium - Hair removal full face', 'price' => 4000],
                    ['name' => 'Alma Soprano Titanium - Hair removal underarms', 'price' => 2000],
                    ['name' => 'Alma Soprano Titanium - Hair removal forearms', 'price' => 2500],
                    ['name' => 'Alma Soprano Titanium - Hair removal upper arms', 'price' => 2500],
                    ['name' => 'Alma Soprano Titanium - Hair removal full arms', 'price' => 4340],
                    ['name' => 'Alma Soprano Titanium - Hair removal Brazilian', 'price' => 3720],
                    ['name' => 'Alma Soprano Titanium - Hair removal buttocks', 'price' => 3900],
                    ['name' => 'Alma Soprano Titanium - Hair removal spine', 'price' => 2000],
                    ['name' => 'Alma Soprano Titanium - Hair removal back', 'price' => 4000],
                    ['name' => 'Alma Soprano Titanium - Hair removal bikini line', 'price' => 2490],
                    ['name' => 'Alma Soprano Titanium - Hair removal above knee with knees', 'price' => 5590],
                    ['name' => 'Alma Soprano Titanium - Hair removal below knee with knees', 'price' => 4980],
                    ['name' => 'Alma Soprano Titanium - Hair removal above knee without knees', 'price' => 4100],
                    ['name' => 'Alma Soprano Titanium - Hair removal below knee without knees', 'price' => 3500],
                    ['name' => 'Alma Soprano Titanium - Hair removal full legs with bikini line', 'price' => 12400],
                    ['name' => 'Alma Soprano Titanium - Hair removal full legs', 'price' => 9910],
                    ['name' => 'Alma Soprano Titanium - Hair removal stomach line', 'price' => 1500],
                    ['name' => 'Alma Soprano Titanium - Hair removal full stomach', 'price' => 3450],
                    ['name' => 'Alma Soprano Titanium - Hair removal men - neck', 'price' => 2480],
                    ['name' => 'Alma Soprano Titanium - Hair removal men - shoulders', 'price' => 3720],
                    ['name' => 'Alma Soprano Titanium - Hair removal men - arms', 'price' => 5580],
                    ['name' => 'Alma Soprano Titanium - Hair removal men - chest and stomach', 'price' => 8680],
                    ['name' => 'Alma Soprano Titanium - Hair removal men - chest', 'price' => 4500],
                    ['name' => 'Alma Soprano Titanium - Hair removal men - stomach', 'price' => 4500],
                    ['name' => 'Alma Soprano Titanium - Hair removal men - back', 'price' => 4340],
                    ['name' => 'Alma Soprano Titanium - Hair removal men - below knee', 'price' => 5800],
                    ['name' => 'Alma Soprano Titanium - Hair removal men - legs', 'price' => 12400],
                    ['name' => 'Alma Soprano Titanium - Hair removal men - chest, stomach and back', 'price' => 12400],
                    ['name' => 'Alma Soprano Titanium - Hair removal men - cheeks', 'price' => 2000],
                    ['name' => 'Alma Soprano Titanium - Hair removal men beard shaping', 'price' => 4000],
                    ['name' => 'Alma Soprano Titanium - Hair removal men front neck', 'price' => 2000],
                    ['name' => 'Alma Soprano Titanium - Hair removal men front + back neck', 'price' => 2500],
                    ['name' => 'Alma Soprano Titanium - Full body hair removal women 1 treatment', 'price' => 18500],
                    ['name' => 'Alma Soprano Titanium - Full body hair removal women 1 treatment (package)', 'price' => 15400],
                    ['name' => 'Alma Soprano Titanium - Full body hair removal MEN 1 treatment', 'price' => 24600],
                    ['name' => 'Alma Soprano Titanium - Full body hair removal MEN 1 treatment (package)', 'price' => 21600],
                    ['name' => 'Alma Soprano Titanium - Package 6 treatments MEN', 'price' => 147600],
                    ['name' => 'Alma Q Lift & Tight face', 'price' => 25000],
                    ['name' => 'Alma Q Lift & Tight face and neck', 'price' => 37200],
                    ['name' => 'Alma Q Lift & Tight neck', 'price' => 18600],
                    ['name' => 'Alma Q periorbital treatment', 'price' => 3100],
                    ['name' => 'Alma Q mouth treatment', 'price' => 3100],
                    ['name' => 'Alma Q under-eye brightening', 'price' => 4000],
                    ['name' => 'Alma Hybrid', 'price' => 24000],
                    ['name' => 'Alma Hybrid mouth', 'price' => 3000],
                    ['name' => 'Alma Hybrid eyes', 'price' => 18500],
                    ['name' => 'Alma Hybrid Soft Lift', 'price' => 15000],
                    ['name' => 'Alma Titanium NIR', 'price' => 4000],
                    ['name' => 'Accent Prime chin with RF+US', 'price' => 4500],
                    ['name' => 'Accent Prime neck and décolleté with RF', 'price' => 4500],
                    ['name' => 'Accent Prime RF full face', 'price' => 5000],
                    ['name' => 'Accent Prime Pixel', 'price' => 6000],
                    ['name' => 'Accent Prime Colibri', 'price' => 3000],
                    ['name' => 'Accent Prime body', 'price' => 2000],
                    ['name' => 'Accent Prime body', 'price' => 3000],
                    ['name' => 'Accent Prime stretch marks', 'price' => 6000],
                    ['name' => 'Ultraformer face', 'price' => 43000],
                    ['name' => 'Ultraformer face without forehead', 'price' => 31000],
                    ['name' => 'Ultraformer chin', 'price' => 12400],
                    ['name' => 'Ultraformer neck', 'price' => 18500],
                    ['name' => 'EM Time 1 Face', 'price' => 3500],
                    ['name' => 'Hydra Facial SIGNATURE', 'price' => 6000],
                    ['name' => 'Hydra Facial DE LUXE', 'price' => 8000],
                    ['name' => 'Hydra Facial PLATINUM', 'price' => 10000],
                    ['name' => 'Hydra Facial Jlo', 'price' => 12000],
                    ['name' => 'Alma Q Carbon Peeling', 'price' => 4000],
                    ['name' => 'Alma Hybrid', 'price' => 24000],
                    ['name' => 'Alma Hybrid papillomas', 'price' => 3000],
                    ['name' => 'Alma Hybrid small scar', 'price' => 10000],
                    ['name' => 'Accent Prime stretch marks', 'price' => 6000],
                    ['name' => 'Alma Q rosacea', 'price' => 4200],
                    ['name' => 'Alma Q rosacea PACKAGE 6 TREATMENTS', 'price' => 20000],
                    ['name' => 'Alma Q MELASMA 1 TREATMENT', 'price' => 15500],
                    ['name' => 'Alma Q capillaries', 'price' => 3000],
                    ['name' => 'Alma Q nail treatment', 'price' => 2000],
                    ['name' => 'Alma Q eyebrow treatment', 'price' => 3100],
                    ['name' => 'PRX Peeling', 'price' => 4800],
                    ['name' => 'Chemical peeling', 'price' => 4000],
                    ['name' => 'Bio C Chemical peeling', 'price' => 3600],
                    ['name' => 'Bio C Chemical peeling + Microneedling', 'price' => 6500],
                    ['name' => 'Chemical peeling periorbital region - 6 treatments', 'price' => 12000],
                    ['name' => 'Microneedling', 'price' => 4500],
                    ['name' => 'Microneedling with Impact', 'price' => 5500],
                ],
            ]);
        } else {
            $category->update([
                'name_en' => 'Laser Treatments',
                'name_mk' => 'Ласерски третмани',
                'description_en' => 'At Babor Medical, we don\'t view laser treatments as isolated procedures, but as part of carefully crafted personalized protocols. Every skin has a different structure, different history and different needs. That\'s why our approach is based on precise assessment and selection of appropriate technology at the right moment. Our strategy is not "one device for all", but a combination of technologies with clear clinical logic.',
                'description_mk' => 'Во Babor Medical, ласерските третмани не ги гледаме како поединечни процедури, туку како дел од внимателно креирани персонализирани протоколи. Секоја кожа има различна структура, различна историја и различни потреби. Затоа нашиот пристап се базира на прецизна проценка и избор на соодветна технологија во вистинскиот момент. Нашата стратегија не е „еден апарат за сите", туку комбинација на технологии со јасна клиничка логика.',
                'extra_data_en' => [
                    'treatment_areas' => [
                        'Pigmentation and sun damage',
                        'Vascular changes and redness',
                        'Unwanted hair',
                        'Scars and post-acne changes',
                        'Uneven texture and enlarged pores',
                        'Signs of aging and loss of elasticity',
                        'Overall improvement of skin quality and tone',
                    ],
                    'approach_strategies' => [
                        'Laser + collagen stimulators',
                        'Laser + RF technologies',
                        'Laser + medical cosmetology (Babor Clinical programs)',
                        'Phased treatment with clearly defined sequence',
                    ],
                    'assessment_points' => [
                        'which technology is most appropriate',
                        'how many treatments are needed',
                        'at what intensity',
                        'whether a combined strategy is needed',
                    ],
                ],
                'extra_data_mk' => [
                    'treatment_areas' => [
                        'Пигментации и сончеви оштетувања',
                        'Васкуларни промени и црвенило',
                        'Нежелана влакнетост',
                        'Лузни и постакне промени',
                        'Нерамна текстура и проширени пори',
                        'Знаци на стареење и губење на еластичност',
                        'Општо подобрување на квалитетот и тонусот на кожата',
                    ],
                    'approach_strategies' => [
                        'Ласер + колаген стимулатори',
                        'Ласер + RF технологии',
                        'Ласер + медицинска козметологија (Babor Clinical програми)',
                        'Фазен третман со јасно дефиниран редослед',
                    ],
                    'assessment_points' => [
                        'која технологија е најсоодветна',
                        'колку третмани се потребни',
                        'со каков интензитет',
                        'дали е потребна комбинирана стратегија',
                    ],
                ],
                'price_list_items_mk' => [
                       ['name' => 'Alma Soprano Titanium - Епилација надусници', 'price' => 1240],
                    ['name' => 'Alma Soprano Titanium - Епилација образи, бекенбарди', 'price' => 1500],
                    ['name' => 'Alma Soprano Titanium - Епилација брада', 'price' => 1240],
                    ['name' => 'Alma Soprano Titanium - Епилација преден дел на врат', 'price' => 1500],
                    ['name' => 'Alma Soprano Titanium - Епилација цело лице', 'price' => 4000],
                    ['name' => 'Alma Soprano Titanium - Епилација пазуви', 'price' => 2000],
                    ['name' => 'Alma Soprano Titanium - Епилација подлактици', 'price' => 2500],
                    ['name' => 'Alma Soprano Titanium - Епилација надлактици', 'price' => 2500],
                    ['name' => 'Alma Soprano Titanium - Епилација цели раце', 'price' => 4340],
                    ['name' => 'Alma Soprano Titanium - Епилација бразилска', 'price' => 3720],
                    ['name' => 'Alma Soprano Titanium - Епилација задник', 'price' => 3900],
                    ['name' => 'Alma Soprano Titanium - Епилација Кичма', 'price' => 2000],
                    ['name' => 'Alma Soprano Titanium - Епилација грб', 'price' => 4000],
                    ['name' => 'Alma Soprano Titanium - Епилација плиток препон', 'price' => 2490],
                    ['name' => 'Alma Soprano Titanium - Епилација надколена со колена', 'price' => 5590],
                    ['name' => 'Alma Soprano Titanium - Епилација подколена со колена', 'price' => 4980],
                    ['name' => 'Alma Soprano Titanium - Епилација надколена без колена', 'price' => 4100],
                    ['name' => 'Alma Soprano Titanium - Епилација подколена без колена', 'price' => 3500],
                    ['name' => 'Alma Soprano Titanium - Епилација цели нозе со плиток препон', 'price' => 12400],
                    ['name' => 'Alma Soprano Titanium - Епилација цели нозе', 'price' => 9910],
                    ['name' => 'Alma Soprano Titanium - Епилација стомачна линија', 'price' => 1500],
                    ['name' => 'Alma Soprano Titanium - Епилација цел стомак', 'price' => 3450],
                    ['name' => 'Alma Soprano Titanium - Епилација за мажи - врат', 'price' => 2480],
                    ['name' => 'Alma Soprano Titanium - Епилација за мажи - рамена', 'price' => 3720],
                    ['name' => 'Alma Soprano Titanium - Епилација за мажи- раце', 'price' => 5580],
                    ['name' => 'Alma Soprano Titanium - Епилација за мажи- гради и стомак', 'price' => 8680],
                    ['name' => 'Alma Soprano Titanium - Епилација за мажи- гради', 'price' => 4500],
                    ['name' => 'Alma Soprano Titanium - Епилација за мажи- stomak', 'price' => 4500],
                    ['name' => 'Alma Soprano Titanium - Епилација за мажи - грб', 'price' => 4340],
                    ['name' => 'Alma Soprano Titanium - Епилација за мажи - подколена', 'price' => 5800],
                    ['name' => 'Alma Soprano Titanium - Епилација за мажи – нозе', 'price' => 12400],
                    ['name' => 'Alma Soprano Titanium - Епилација за мажи - гради, стомак и грб', 'price' => 12400],
                    ['name' => 'Alma Soprano Titanium - Епилација за мажи – образи', 'price' => 2000],
                    ['name' => 'Alma Soprano Titanium - Епилација маски обликување брада', 'price' => 4000],
                    ['name' => 'Alma Soprano Titanium - Епилација мажи преден дел врат', 'price' => 2000],
                    ['name' => 'Alma Soprano Titanium - Епилација мажи преден дел врат+заден', 'price' => 2500],
                    ['name' => 'Alma Soprano Titanium - Епилација цело тело жени 1 третман', 'price' => 18500],
                    ['name' => 'Alma Soprano Titanium - Епилација цело тело жени 1 третман во пакет', 'price' => 15400],
                    ['name' => 'Alma Soprano Titanium - Епилација цело тело МАЖИ 1 третман', 'price' => 24600],
                    ['name' => 'Alma Soprano Titanium - Епилација цело тело МАЖИ 1 третман во пакет', 'price' => 21600],
                    ['name' => 'Alma Soprano Titanium - Пакет од 6 третмани МАЖИ', 'price' => 147600],
                    ['name' => 'Alma Q Lift & Tight лице', 'price' => 25000],
                    ['name' => 'Alma Q Lift & Tight лице и врат', 'price' => 37200],
                    ['name' => 'Alma Q Lift & Tight врат', 'price' => 18600],
                    ['name' => 'Alma Q третман за околуочна регија', 'price' => 3100],
                    ['name' => 'Alma Q третман за уста', 'price' => 3100],
                    ['name' => 'Alma Q избелување подочници', 'price' => 4000],
                    ['name' => 'Alma Hybrid', 'price' => 24000],
                    ['name' => 'Alma Hybrid уста', 'price' => 3000],
                    ['name' => 'Alma Hybrid очи', 'price' => 18500],
                    ['name' => 'Allma Hybrid Soft Lift', 'price' => 15000],
                    ['name' => 'Alma Titanium NIR', 'price' => 4000],
                    ['name' => 'Accent Prime подбрадок со РФ+УЗ', 'price' => 4500],
                    ['name' => 'Accent Prime врат и деколте со РФ', 'price' => 4500],
                    ['name' => 'Accent Prime РФ на цело лице', 'price' => 5000],
                    ['name' => 'Accent Prime Pixel', 'price' => 6000],
                    ['name' => 'Accent Prime Colibri', 'price' => 3000],
                    ['name' => 'Accent Prime на тело', 'price' => 2000],
                    ['name' => 'Accent Prime на тело', 'price' => 3000],
                    ['name' => 'Accent Prime стрии', 'price' => 6000],
                    ['name' => 'Ultraformer lice', 'price' => 43000],
                    ['name' => 'Ultraformer lice bez celo', 'price' => 31000],
                    ['name' => 'Ultraformer подбрадок', 'price' => 12400],
                    ['name' => 'Ultraformer врат', 'price' => 18500],
                    ['name' => 'EM Time 1 Lice', 'price' => 3500],
                    ['name' => 'Hydra Facial SYGNITURE', 'price' => 6000],
                    ['name' => 'Hydra Facial DE LUXE', 'price' => 8000],
                    ['name' => 'Hydra Facial PLATINUM', 'price' => 10000],
                    ['name' => 'Hydra Facial Jlo', 'price' => 12000],
                    ['name' => 'Alma Q Carbon Peeling', 'price' => 4000],
                    ['name' => 'Alma Hybrid', 'price' => 24000],
                    ['name' => 'Alma Hybrid папиломи', 'price' => 3000],
                    ['name' => 'Allma Hybrid мала лузна', 'price' => 10000],
                    ['name' => 'Accent Prime стрии', 'price' => 6000],
                    ['name' => 'Alma Q розацеа', 'price' => 4200],
                    ['name' => 'Alma Q розацеа ПАКЕТ 6 ТРЕТМАНИ', 'price' => 20000],
                    ['name' => 'Alma Q МЕЛАЗМА 1 ТРЕТМАН', 'price' => 15500],
                    ['name' => 'Alma Q капилари', 'price' => 3000],
                    ['name' => 'Alma Q третман на нокти', 'price' => 2000],
                    ['name' => 'Alma Q третман за веѓи', 'price' => 3100],
                    ['name' => 'PRX Пилинг', 'price' => 4800],
                    ['name' => 'Хемиски пилинг', 'price' => 4000],
                    ['name' => 'Био Ц Хемиски пилинг', 'price' => 3600],
                    ['name' => 'Био Ц Хемиски пилинг + Микронидлинг', 'price' => 6500],
                    ['name' => 'Хемиски пилинг за околуочна регија - 6 тертмани', 'price' => 12000],
                    ['name' => 'Микронидлинг', 'price' => 4500],
                    ['name' => 'Микронидлинг со Impact', 'price' => 5500],
                ],
                'price_list_items_en' => [
                             ['name' => 'Alma Soprano Titanium - Hair removal upper lip', 'price' => 1240],
                    ['name' => 'Alma Soprano Titanium - Hair removal cheeks, sideburns', 'price' => 1500],
                    ['name' => 'Alma Soprano Titanium - Hair removal chin', 'price' => 1240],
                    ['name' => 'Alma Soprano Titanium - Hair removal front of neck', 'price' => 1500],
                    ['name' => 'Alma Soprano Titanium - Hair removal full face', 'price' => 4000],
                    ['name' => 'Alma Soprano Titanium - Hair removal underarms', 'price' => 2000],
                    ['name' => 'Alma Soprano Titanium - Hair removal forearms', 'price' => 2500],
                    ['name' => 'Alma Soprano Titanium - Hair removal upper arms', 'price' => 2500],
                    ['name' => 'Alma Soprano Titanium - Hair removal full arms', 'price' => 4340],
                    ['name' => 'Alma Soprano Titanium - Hair removal Brazilian', 'price' => 3720],
                    ['name' => 'Alma Soprano Titanium - Hair removal buttocks', 'price' => 3900],
                    ['name' => 'Alma Soprano Titanium - Hair removal spine', 'price' => 2000],
                    ['name' => 'Alma Soprano Titanium - Hair removal back', 'price' => 4000],
                    ['name' => 'Alma Soprano Titanium - Hair removal bikini line', 'price' => 2490],
                    ['name' => 'Alma Soprano Titanium - Hair removal above knee with knees', 'price' => 5590],
                    ['name' => 'Alma Soprano Titanium - Hair removal below knee with knees', 'price' => 4980],
                    ['name' => 'Alma Soprano Titanium - Hair removal above knee without knees', 'price' => 4100],
                    ['name' => 'Alma Soprano Titanium - Hair removal below knee without knees', 'price' => 3500],
                    ['name' => 'Alma Soprano Titanium - Hair removal full legs with bikini line', 'price' => 12400],
                    ['name' => 'Alma Soprano Titanium - Hair removal full legs', 'price' => 9910],
                    ['name' => 'Alma Soprano Titanium - Hair removal stomach line', 'price' => 1500],
                    ['name' => 'Alma Soprano Titanium - Hair removal full stomach', 'price' => 3450],
                    ['name' => 'Alma Soprano Titanium - Hair removal men - neck', 'price' => 2480],
                    ['name' => 'Alma Soprano Titanium - Hair removal men - shoulders', 'price' => 3720],
                    ['name' => 'Alma Soprano Titanium - Hair removal men - arms', 'price' => 5580],
                    ['name' => 'Alma Soprano Titanium - Hair removal men - chest and stomach', 'price' => 8680],
                    ['name' => 'Alma Soprano Titanium - Hair removal men - chest', 'price' => 4500],
                    ['name' => 'Alma Soprano Titanium - Hair removal men - stomach', 'price' => 4500],
                    ['name' => 'Alma Soprano Titanium - Hair removal men - back', 'price' => 4340],
                    ['name' => 'Alma Soprano Titanium - Hair removal men - below knee', 'price' => 5800],
                    ['name' => 'Alma Soprano Titanium - Hair removal men - legs', 'price' => 12400],
                    ['name' => 'Alma Soprano Titanium - Hair removal men - chest, stomach and back', 'price' => 12400],
                    ['name' => 'Alma Soprano Titanium - Hair removal men - cheeks', 'price' => 2000],
                    ['name' => 'Alma Soprano Titanium - Hair removal men beard shaping', 'price' => 4000],
                    ['name' => 'Alma Soprano Titanium - Hair removal men front neck', 'price' => 2000],
                    ['name' => 'Alma Soprano Titanium - Hair removal men front + back neck', 'price' => 2500],
                    ['name' => 'Alma Soprano Titanium - Full body hair removal women 1 treatment', 'price' => 18500],
                    ['name' => 'Alma Soprano Titanium - Full body hair removal women 1 treatment (package)', 'price' => 15400],
                    ['name' => 'Alma Soprano Titanium - Full body hair removal MEN 1 treatment', 'price' => 24600],
                    ['name' => 'Alma Soprano Titanium - Full body hair removal MEN 1 treatment (package)', 'price' => 21600],
                    ['name' => 'Alma Soprano Titanium - Package 6 treatments MEN', 'price' => 147600],
                    ['name' => 'Alma Q Lift & Tight face', 'price' => 25000],
                    ['name' => 'Alma Q Lift & Tight face and neck', 'price' => 37200],
                    ['name' => 'Alma Q Lift & Tight neck', 'price' => 18600],
                    ['name' => 'Alma Q periorbital treatment', 'price' => 3100],
                    ['name' => 'Alma Q mouth treatment', 'price' => 3100],
                    ['name' => 'Alma Q under-eye brightening', 'price' => 4000],
                    ['name' => 'Alma Hybrid', 'price' => 24000],
                    ['name' => 'Alma Hybrid mouth', 'price' => 3000],
                    ['name' => 'Alma Hybrid eyes', 'price' => 18500],
                    ['name' => 'Alma Hybrid Soft Lift', 'price' => 15000],
                    ['name' => 'Alma Titanium NIR', 'price' => 4000],
                    ['name' => 'Accent Prime chin with RF+US', 'price' => 4500],
                    ['name' => 'Accent Prime neck and décolleté with RF', 'price' => 4500],
                    ['name' => 'Accent Prime RF full face', 'price' => 5000],
                    ['name' => 'Accent Prime Pixel', 'price' => 6000],
                    ['name' => 'Accent Prime Colibri', 'price' => 3000],
                    ['name' => 'Accent Prime body', 'price' => 2000],
                    ['name' => 'Accent Prime body', 'price' => 3000],
                    ['name' => 'Accent Prime stretch marks', 'price' => 6000],
                    ['name' => 'Ultraformer face', 'price' => 43000],
                    ['name' => 'Ultraformer face without forehead', 'price' => 31000],
                    ['name' => 'Ultraformer chin', 'price' => 12400],
                    ['name' => 'Ultraformer neck', 'price' => 18500],
                    ['name' => 'EM Time 1 Face', 'price' => 3500],
                    ['name' => 'Hydra Facial SIGNATURE', 'price' => 6000],
                    ['name' => 'Hydra Facial DE LUXE', 'price' => 8000],
                    ['name' => 'Hydra Facial PLATINUM', 'price' => 10000],
                    ['name' => 'Hydra Facial Jlo', 'price' => 12000],
                    ['name' => 'Alma Q Carbon Peeling', 'price' => 4000],
                    ['name' => 'Alma Hybrid', 'price' => 24000],
                    ['name' => 'Alma Hybrid papillomas', 'price' => 3000],
                    ['name' => 'Alma Hybrid small scar', 'price' => 10000],
                    ['name' => 'Accent Prime stretch marks', 'price' => 6000],
                    ['name' => 'Alma Q rosacea', 'price' => 4200],
                    ['name' => 'Alma Q rosacea PACKAGE 6 TREATMENTS', 'price' => 20000],
                    ['name' => 'Alma Q MELASMA 1 TREATMENT', 'price' => 15500],
                    ['name' => 'Alma Q capillaries', 'price' => 3000],
                    ['name' => 'Alma Q nail treatment', 'price' => 2000],
                    ['name' => 'Alma Q eyebrow treatment', 'price' => 3100],
                    ['name' => 'PRX Peeling', 'price' => 4800],
                    ['name' => 'Chemical peeling', 'price' => 4000],
                    ['name' => 'Bio C Chemical peeling', 'price' => 3600],
                    ['name' => 'Bio C Chemical peeling + Microneedling', 'price' => 6500],
                    ['name' => 'Chemical peeling periorbital region - 6 treatments', 'price' => 12000],
                    ['name' => 'Microneedling', 'price' => 4500],
                    ['name' => 'Microneedling with Impact', 'price' => 5500],
                ],
            ]);
        }

        $category->items()->delete();

        $treatments = [
            [
                'name_en' => 'Alma Q',
                'name_mk' => 'Alma Q',
                'subtitle_en' => 'Q-switched laser for pigmentation, tattoos and skin revitalization',
                'subtitle_mk' => 'Q-switched ласер за третман на пигментации, тетоважи и ревитализација на кожата',
                'description_en' => '<p>Provides high precision and controlled energy with minimal impact on surrounding tissue.</p>',
                'description_mk' => '<p>Обезбедува висока прецизност и контролирана енергија со минимално оптоварување на околното ткиво.</p>',
                'indications_en' => '<ul><li>Pigmentation and sun damage</li><li>Tattoo removal</li><li>Skin revitalization</li><li>Uneven skin tone</li></ul>',
                'indications_mk' => '<ul><li>Пигментации и сончеви оштетувања</li><li>Отстранување на тетоважи</li><li>Ревитализација на кожата</li><li>Нерамномерен тен</li></ul>',
                'includes_en' => null,
                'includes_mk' => null,
                'components_en' => null,
                'components_mk' => null,
                'effects_en' => '<ul><li>Targeted pigment destruction</li><li>Stimulation of collagen production</li><li>Improved skin tone and texture</li><li>Minimal downtime</li></ul>',
                'effects_mk' => '<ul><li>Таргетирано уништување на пигмент</li><li>Стимулација на продукција на колаген</li><li>Подобрен тон и текстура на кожата</li><li>Минимално време на опоравување</li></ul>',
                'suitable_for_en' => null,
                'suitable_for_mk' => null,
                'note_en' => null,
                'note_mk' => null,
                'sort_order' => 1,
            ],
            [
                'name_en' => 'Alma Hybrid',
                'name_mk' => 'Alma Hybrid',
                'subtitle_en' => 'Fractional CO2 and non-ablative laser in one system',
                'subtitle_mk' => 'Фракционен CO2 и не-аблативен ласер во еден систем',
                'description_en' => '<p>Used for scar treatment, skin regeneration, texture improvement and anti-age strategies.</p>',
                'description_mk' => '<p>Се користи за третман на лузни, регенерација на кожа, подобрување на текстура и anti-age стратегии.</p>',
                'indications_en' => '<ul><li>Scars and post-acne changes</li><li>Uneven texture and enlarged pores</li><li>Signs of aging and loss of elasticity</li><li>Skin regeneration</li></ul>',
                'indications_mk' => '<ul><li>Лузни и постакне промени</li><li>Нерамна текстура и проширени пори</li><li>Знаци на стареење и губење на еластичност</li><li>Регенерација на кожа</li></ul>',
                'includes_en' => null,
                'includes_mk' => null,
                'components_en' => null,
                'components_mk' => null,
                'effects_en' => '<ul><li>Deep skin regeneration</li><li>Collagen remodeling</li><li>Improved skin texture</li><li>Tightening and firming</li></ul>',
                'effects_mk' => '<ul><li>Длабока регенерација на кожата</li><li>Ремоделирање на колаген</li><li>Подобрена текстура на кожата</li><li>Затегнување и зацврстување</li></ul>',
                'suitable_for_en' => null,
                'suitable_for_mk' => null,
                'note_en' => null,
                'note_mk' => null,
                'sort_order' => 2,
            ],
            [
                'name_en' => 'Ultraformer III',
                'name_mk' => 'Ultraformer III',
                'subtitle_en' => 'HIFU technology for non-invasive lifting and structural face support',
                'subtitle_mk' => 'HIFU технологија за неинвазивен лифтинг и структурна поддршка на лицето',
                'description_en' => '<p>Often part of combined protocols for tightening and contour improvement.</p>',
                'description_mk' => '<p>Често е дел од комбинирани протоколи за зацврстување и подобрување на контурата.</p>',
                'indications_en' => '<ul><li>Loss of tone and sagging</li><li>Loss of facial contour</li><li>Fine lines and wrinkles</li><li>Skin laxity</li></ul>',
                'indications_mk' => '<ul><li>Губење на тонус и опуштеност</li><li>Губење на контура на лицето</li><li>Фини линии и брчки</li><li>Лабавост на кожата</li></ul>',
                'includes_en' => null,
                'includes_mk' => null,
                'components_en' => null,
                'components_mk' => null,
                'effects_en' => '<ul><li>Non-invasive lifting</li><li>Structural support</li><li>Contour improvement</li><li>Collagen stimulation in deep layers</li></ul>',
                'effects_mk' => '<ul><li>Неинвазивен лифтинг</li><li>Структурна поддршка</li><li>Подобрување на контурата</li><li>Стимулација на колаген во длабоки слоеви</li></ul>',
                'suitable_for_en' => null,
                'suitable_for_mk' => null,
                'note_en' => null,
                'note_mk' => null,
                'sort_order' => 3,
            ],
            [
                'name_en' => 'DPL / IPL System',
                'name_mk' => 'DPL / IPL систем',
                'subtitle_en' => 'Technology for pigmentation, capillaries and photorejuvenation',
                'subtitle_mk' => 'Технологија за третман на пигментации, капилари и фотоподмладување',
                'description_en' => '<p>Enables skin tone refreshment and color evening.</p>',
                'description_mk' => '<p>Овозможува освежување на тенот и изедначување на бојата на кожата.</p>',
                'indications_en' => '<ul><li>Pigmentation</li><li>Vascular changes and redness</li><li>Photoaging</li><li>Dull skin without vitality</li></ul>',
                'indications_mk' => '<ul><li>Пигментации</li><li>Васкуларни промени и црвенило</li><li>Фотостареење</li><li>Уморна кожа без виталност</li></ul>',
                'includes_en' => null,
                'includes_mk' => null,
                'components_en' => null,
                'components_mk' => null,
                'effects_en' => '<ul><li>Skin tone refreshment</li><li>Color evening</li><li>Reduction of redness</li><li>Overall rejuvenation</li></ul>',
                'effects_mk' => '<ul><li>Освежување на тенот</li><li>Изедначување на бојата</li><li>Намалување на црвенило</li><li>Целосно подмладување</li></ul>',
                'suitable_for_en' => null,
                'suitable_for_mk' => null,
                'note_en' => null,
                'note_mk' => null,
                'sort_order' => 4,
            ],
        ];

        foreach ($treatments as $treatment) {
            ServiceItem::create(array_merge($treatment, [
                'service_category_id' => $category->id,
                'is_expandable' => true,
                'is_active' => true,
            ]));
        }
    }
}
